// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-cq37OsnAkk4jautCXa2JqZVEKL0YOI',
    appId: '1:581630773747:web:ebfa36329f65f7fee3aa86',
    messagingSenderId: '581630773747',
    projectId: 'besheger-services',
    authDomain: 'besheger-services.firebaseapp.com',
    storageBucket: 'besheger-services.appspot.com',
    measurementId: 'G-CTFXLT5HRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2lSTPCEf4FSEQvUTh2DcTrcwNy7qHa7k',
    appId: '1:581630773747:android:0efa0d9633dc46c4e3aa86',
    messagingSenderId: '581630773747',
    projectId: 'besheger-services',
    storageBucket: 'besheger-services.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqI53M5ubFu01tSHKvyj-UGMJjiMSZ31M',
    appId: '1:581630773747:ios:6b35e10136658e6fe3aa86',
    messagingSenderId: '581630773747',
    projectId: 'besheger-services',
    storageBucket: 'besheger-services.appspot.com',
    iosBundleId: 'com.besheger.negade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqI53M5ubFu01tSHKvyj-UGMJjiMSZ31M',
    appId: '1:581630773747:ios:99a67a6ef376bf53e3aa86',
    messagingSenderId: '581630773747',
    projectId: 'besheger-services',
    storageBucket: 'besheger-services.appspot.com',
    iosBundleId: 'com.besheger.negade.RunnerTests',
  );
}
